import React, { useState } from 'react';
import { View, Text, Image, ScrollView, StyleSheet, TouchableOpacity, Alert } from 'react-native';
import { useEvents } from '../context/EventContext';
import CustomButton from '../components/CustomButton';
import { colors, radii } from '../constants/theme';

export default function EventDetailScreen({ route, navigation }) {
  const { event } = route.params;
  const { favorites, toggleFavorite, buyTicket, tickets } = useEvents();
  const [favorite, setFavorite] = useState(favorites.includes(event.id));
  const booked = tickets.some((ticket) => ticket.id === event.id);
  const buy = async () => { if (booked) return; await buyTicket(event); Alert.alert('Booking confirmed', 'Your ticket is now in My tickets.'); };
  return <ScrollView style={styles.background} showsVerticalScrollIndicator={false}>
    <View><Image source={{ uri: event.image }} style={styles.image} /><TouchableOpacity style={styles.back} onPress={() => navigation.goBack()}><Text style={styles.backText}>‹</Text></TouchableOpacity><TouchableOpacity style={styles.favorite} onPress={() => { toggleFavorite(event.id); setFavorite(!favorite); }}><Text style={styles.favoriteText}>{favorite ? '♥' : '♡'}</Text></TouchableOpacity></View>
    <View style={styles.content}><Text style={styles.category}>{event.category}</Text><Text style={styles.title}>{event.title}</Text><View style={styles.info}><Text style={styles.infoIcon}>◷</Text><View><Text style={styles.infoLabel}>DATE & TIME</Text><Text style={styles.infoText}>{event.date} · {event.time}</Text></View></View><View style={styles.info}><Text style={styles.infoIcon}>⌖</Text><View><Text style={styles.infoLabel}>LOCATION</Text><Text style={styles.infoText}>{event.location}</Text></View></View><Text style={styles.heading}>About this event</Text><Text style={styles.description}>{event.description}</Text><View style={styles.bottom}><View><Text style={styles.priceLabel}>TICKET PRICE</Text><Text style={styles.price}>{event.price ? `${event.price.toLocaleString('vi-VN')} đ` : 'Free'}</Text></View><View style={styles.button}><CustomButton title={booked ? 'Booked ✓' : 'Book now'} onPress={buy} /></View></View></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ background: { flex: 1, backgroundColor: colors.background }, image: { width: '100%', height: 320 }, back: { position: 'absolute', top: 48, left: 18, width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.94)', alignItems: 'center', justifyContent: 'center' }, backText: { color: colors.ink, fontSize: 34, lineHeight: 37 }, favorite: { position: 'absolute', top: 48, right: 18, width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.94)', alignItems: 'center', justifyContent: 'center' }, favoriteText: { color: colors.primary, fontSize: 28 }, content: { padding: 22, marginTop: -24, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.background }, category: { color: colors.primary, fontSize: 12, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.ink, fontSize: 30, lineHeight: 35, fontWeight: '900', marginTop: 8 }, info: { flexDirection: 'row', alignItems: 'center', marginTop: 20 }, infoIcon: { width: 38, height: 38, borderRadius: 12, color: colors.primary, backgroundColor: colors.primarySoft, textAlign: 'center', textAlignVertical: 'center', fontSize: 21, marginRight: 12 }, infoLabel: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, infoText: { color: colors.ink, fontSize: 14, fontWeight: '700', marginTop: 4, maxWidth: 290 }, heading: { color: colors.ink, fontSize: 20, fontWeight: '900', marginTop: 28 }, description: { color: colors.muted, fontSize: 15, lineHeight: 23, marginTop: 9 }, bottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 26, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.line }, priceLabel: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, price: { color: colors.ink, fontSize: 20, fontWeight: '900', marginTop: 3 }, button: { width: 145 } });
