import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet, Alert, ScrollView } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { colors, radii } from '../constants/theme';

export default function ProfileScreen() {
	const { user, logout } = useAuth();
	const confirmLogout = () => Alert.alert('Log out', 'Are you sure you want to log out?', [{ text: 'Cancel' }, { text: 'Log out', onPress: logout }]);
	return <ScrollView style={styles.background} contentContainerStyle={styles.container}><Text style={styles.kicker}>YOUR SPACE</Text><Text style={styles.title}>Profile</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.name?.[0]?.toUpperCase() || 'U'}</Text></View><View><Text style={styles.name}>{user?.name || 'Event Explorer'}</Text><Text style={styles.email}>{user?.email}</Text></View></View><View style={styles.menu}><Text style={styles.menuTitle}>ACCOUNT</Text><TouchableOpacity style={styles.item}><Text style={styles.itemIcon}>◉</Text><Text style={styles.itemText}>Personal information</Text><Text style={styles.chevron}>›</Text></TouchableOpacity><TouchableOpacity style={styles.item}><Text style={styles.itemIcon}>⌁</Text><Text style={styles.itemText}>Notifications</Text><Text style={styles.chevron}>›</Text></TouchableOpacity><TouchableOpacity style={styles.item}><Text style={styles.itemIcon}>⚙</Text><Text style={styles.itemText}>Settings</Text><Text style={styles.chevron}>›</Text></TouchableOpacity></View><TouchableOpacity style={styles.logout} onPress={confirmLogout}><Text style={styles.logoutText}>Log out</Text></TouchableOpacity></ScrollView>;
}
const styles = StyleSheet.create({ background: { flex: 1, backgroundColor: colors.background }, container: { padding: 22, paddingTop: 28 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: '900', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 32, fontWeight: '900', marginTop: 8 }, profile: { flexDirection: 'row', alignItems: 'center', paddingVertical: 28 }, avatar: { width: 68, height: 68, borderRadius: 24, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginRight: 15 }, avatarText: { color: colors.surface, fontSize: 30, fontWeight: '900' }, name: { color: colors.ink, fontSize: 19, fontWeight: '900' }, email: { color: colors.muted, marginTop: 4 }, menu: { padding: 18, borderRadius: radii.large, backgroundColor: colors.surface }, menuTitle: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.5, marginBottom: 6 }, item: { height: 58, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line }, itemIcon: { width: 30, color: colors.primary, fontSize: 21 }, itemText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '700' }, chevron: { color: colors.muted, fontSize: 25 }, logout: { height: 54, borderRadius: radii.medium, backgroundColor: '#FDECEF', alignItems: 'center', justifyContent: 'center', marginTop: 20 }, logoutText: { color: colors.danger, fontWeight: '900' } });
