import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, Alert, KeyboardAvoidingView, Platform } from 'react-native';
import { useAuth } from '../context/AuthContext';
import CustomButton from '../components/CustomButton';
import { colors, radii } from '../constants/theme';

export default function RegisterScreen({ navigation }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const { register } = useAuth();
  const submit = async () => { try { await register(name, email, password); } catch (error) { Alert.alert('Notice', error.message); } };
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.background}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹  Back</Text></TouchableOpacity><Text style={styles.kicker}>JOIN THE COMMUNITY</Text><Text style={styles.title}>Create your account.</Text><Text style={styles.subtitle}>Save events and keep every plan close.</Text><Text style={styles.label}>FULL NAME</Text><TextInput placeholder="Your name" placeholderTextColor={colors.muted} value={name} onChangeText={setName} style={styles.input} /><Text style={styles.label}>EMAIL ADDRESS</Text><TextInput placeholder="you@example.com" placeholderTextColor={colors.muted} value={email} onChangeText={setEmail} style={styles.input} keyboardType="email-address" autoCapitalize="none" /><Text style={styles.label}>PASSWORD</Text><TextInput placeholder="Create a password" placeholderTextColor={colors.muted} value={password} onChangeText={setPassword} style={styles.input} secureTextEntry /><CustomButton title="Create account" onPress={submit} /><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.link}>Already have an account? <Text style={styles.linkStrong}>Log in</Text></Text></TouchableOpacity></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ background: { flex: 1, backgroundColor: colors.background, padding: 25, justifyContent: 'center' }, back: { color: colors.primary, fontSize: 15, fontWeight: '900', marginBottom: 48 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: '900', letterSpacing: 1.5 }, title: { color: colors.ink, fontSize: 32, fontWeight: '900', marginTop: 10 }, subtitle: { color: colors.muted, fontSize: 15, marginTop: 9, marginBottom: 22 }, label: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.2, marginBottom: 7, marginTop: 10 }, input: { height: 54, borderRadius: radii.medium, backgroundColor: colors.surface, paddingHorizontal: 16, color: colors.ink, fontSize: 15 }, link: { textAlign: 'center', color: colors.muted, fontSize: 13, marginTop: 22 }, linkStrong: { color: colors.primary, fontWeight: '900' } });
