import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useEvents } from '../context/EventContext';
import { colors, radii } from '../constants/theme';

export default function TicketScreen() {
  const { tickets } = useEvents();
  return <ScrollView style={styles.background} contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}><Text style={styles.kicker}>YOUR PLANS</Text><Text style={styles.title}>My tickets</Text><Text style={styles.subtitle}>Everything you have booked, in one place.</Text>{tickets.length ? tickets.map((event) => <View key={event.id} style={styles.ticket}><View style={styles.ticketTop}><View><Text style={styles.category}>{event.category}</Text><Text style={styles.name}>{event.title}</Text></View><Text style={styles.status}>CONFIRMED</Text></View><View style={styles.detailRow}><Text style={styles.detailIcon}>◷</Text><Text style={styles.detail}>{event.date} · {event.time}</Text></View><View style={styles.detailRow}><Text style={styles.detailIcon}>⌖</Text><Text style={styles.detail}>{event.location}</Text></View><View style={styles.divider} /><Text style={styles.codeLabel}>TICKET CODE</Text><Text style={styles.code}>EVENTHUB · {event.id.toUpperCase()} · {event.date.replaceAll('/', '')}</Text></View>) : <View style={styles.empty}><Text style={styles.emptyIcon}>▱</Text><Text style={styles.emptyTitle}>No tickets yet</Text><Text style={styles.emptyText}>Your booked events will appear here.</Text></View>}</ScrollView>;
}
const styles = StyleSheet.create({ background: { flex: 1, backgroundColor: colors.background }, container: { padding: 20, paddingTop: 28, paddingBottom: 30 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: '900', letterSpacing: 2 }, title: { color: colors.ink, fontSize: 32, fontWeight: '900', marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 14, marginTop: 7, marginBottom: 24 }, ticket: { padding: 18, borderRadius: radii.large, backgroundColor: colors.surface, marginBottom: 16 }, ticketTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, category: { color: colors.primary, fontSize: 11, fontWeight: '900' }, name: { color: colors.ink, fontSize: 18, fontWeight: '900', marginTop: 5, maxWidth: 210 }, status: { color: '#37A889', fontSize: 9, fontWeight: '900', letterSpacing: 1 }, detailRow: { flexDirection: 'row', alignItems: 'center', marginTop: 16 }, detailIcon: { color: colors.primary, fontSize: 18, width: 25 }, detail: { color: colors.muted, fontSize: 13, flex: 1 }, divider: { borderTopWidth: 1, borderStyle: 'dashed', borderTopColor: colors.line, marginTop: 18, paddingTop: 15 }, codeLabel: { color: colors.muted, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, code: { color: colors.ink, fontSize: 12, fontWeight: '900', marginTop: 6 }, empty: { alignItems: 'center', marginTop: 100 }, emptyIcon: { color: colors.primary, fontSize: 70 }, emptyTitle: { color: colors.ink, fontSize: 20, fontWeight: '900', marginTop: 12 }, emptyText: { color: colors.muted, marginTop: 7 } });
